language: node_js
node_js:
  # This ensures that all Travis jobs run consistently and don't have different Node versions.
  - '10.8.0'
dist: trusty
sudo: false

branches:
   only:
      - master

script:
  - npm run lint
  - npm run test:headless
  - npm run build:prod

cache:
  directories:
    - ./node_modules/

deploy:
  local-dir: 'dist/video-query'
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
