language: node_js
node_js:
  # This ensures that all Travis jobs run consistently and don't have different Node versions.
  - '10.8.0'
dist: trusty
sudo: false

branches:
   only:
      - master

script:
  - npm run lint
  - npm run test:headless
  - npm run build

cache:
  directories:
    - ./node_modules/
