language: node_js
dist: trusty
sudo: false

node_js:
  # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  # This ensures that all Travis jobs run consistently and don't have different Node versions.
  - '10.8.0'

branches:
   only:
      - master

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run lint
  # - ng test --watch=false
  # - bg build --prod

cache:
  directories:
    - ./node_modules/
